version: '3'
services:
  opencart_v2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
      - "2121:21"
    depends_on:
      - db_opencart_v2
    restart: always
    environment:
      DB_HOST: db_opencart_v2:3306
      DB_USER: 'opencart'
      DB_PASSWORD: 'opencart'
      DB_DATABASE: 'opencart'
      OC_USER: 'admin'
      OC_PASSWORD: 'admin'
      OC_EMAIL: 'your-email@example.com'
      OC_HTTP_SERVER: 'http://localhost:8090/'
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=Docker

  db_opencart_v2:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart
      MYSQL_ROOT_PASSWORD: opencart
volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/mysql_data
